spring:
  profiles:
    active: native
  application:
    name: microservices 
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
server:
  port: 1996